### ISSUE TITLE
Wish: CMAKE-based buildsystem

### ISSUE THREAD

**Issue by nielsvm** [soramimi/Guitar#31] opened 2018-11-10 10:35 UTC
Hello there!

Thank you for building this wonderful application, the world really needs a good and simple GIT GUI :-)

I discovered your application through **HaukuDepot** and not through any of the Linux packaging systems. I suspect that your project could get more exposure and adoption if it had a CMake-based build procedure, which is the _de facto_ (and soon official) standard for many Qt projects:
http://doc.qt.io/qtcreator/creator-project-cmake.html

Not only will Linux distro packagers find it easier to package it, manual compilation will be a simple matter of these standard commands:
```
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr sudo make install
```

Let me know if you're interested in my help!

PS. Cmake supports Mac/Win/Linux and other platforms.

Thank you,
Niels

**Comment by soramimi** [comment] 2018-11-10 10:58
Hi, Niels

I am not good at CMake, so it is difficult to realize it soon, but someone is trying to do it. I might merge it in the near future. Your request is not impossible. Please watch his repository for a while.

https://github.com/ruimaciel/Guitar/commits/cmake_migration

**Comment by nielsvm** [comment] 2018-11-10 11:02
Yeah CMake takes a bit of getting used too but its also pervasive and widely used. I'll watch that repository and see if I can help @ruimaciel with testing or contributions.

**Comment by gombosg** [comment] 2019-02-20 16:14
Let me know if there are some advances since then this could be included in some major Linux distros. E.g. I could package it for Fedora.

**Comment by soramimi** [comment] 2019-02-21 00:22
Since it was already done, in Ubuntu and macOS, you should be able to use CMake. However, on Windows, it is difficult to prepare OpenSSL and zlib, so I have not confirmed it. Also I have not confirmed other distributions of Linux.

**Comment by gombosg** [comment] 2019-02-21 02:16
WOW! Runs just fine. I'll try to create a specfile then for an RPM.

**Comment by soramimi** [comment] 2019-02-21 03:22
On Linux, the Guitar works with one binary file. There is no installation information. Just copy the file to `/usr/local/bin` etc. The Guitar depends on Qt 5, OpenSSL and Zlib. Please consider it when you make the package. The example of launcher file and icon file for X Window are in the `Guitar/LinuxDesktop` directory.

**Comment by ruimaciel** [comment] 2019-02-21 20:30
@gombosg That's good to hear.  The migration to cmake required moving some stuff around the project tree and I was expecting a bumpy ride.  I'm glad that my concerns didn't materialized.

**Comment by mikiTesf** [comment] 2019-09-05 12:23
Why is this issue still open?

**Comment by soramimi** [comment] 2019-09-05 12:45
I forgot to close this issue. no reason.

**Closed by soramimi** 2019-09-05 12:45 UTC
